# Generated by Django 4.2.4 on 2023-08-31 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categoria', '0002_categorias_fecharegistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_product', models.CharField(max_length=250)),
                ('nombre_producto', models.CharField(max_length=250)),
                ('descripcion_producto', models.CharField(blank=True, max_length=300)),
                ('cantidad', models.IntegerField()),
                ('alerta', models.IntegerField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='documentoCompra',
            fields=[
                ('id_factura' , models.AutoField(primary_key=True, serialize=False)),
                ('num_factura', models.CharField(max_length=250)),
                ('serie_factura', models.CharField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('fecha_registro', models.DateField()),
                ('cod_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioAPP.inventario')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
