# Generated by Django 4.2.4 on 2023-09-25 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evento', '0001_initial'),
        ('facturacion', '0002_delete_facturacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='facturacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_interno', models.CharField(max_length=100)),
                ('num_factura', models.CharField(max_length=100)),
                ('serie_factura', models.CharField(max_length=100)),
                ('nit_factura', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('totalFact', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaFacturacion', models.DateField()),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.evento')),
            ],
        ),
        migrations.CreateModel(
            name='detalleFacturacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precioU', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_interno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.facturacion')),
            ],
        ),
    ]
