# Generated by Django 4.2.4 on 2023-09-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacion',
            name='num_autorizacion',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
