# Generated by Django 4.2.4 on 2023-09-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehiculos',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_vehiculo', models.CharField(max_length=300)),
                ('modelo', models.CharField(max_length=300)),
                ('marca', models.CharField(max_length=300)),
                ('placas', models.CharField(max_length=300)),
            ],
        ),
    ]
