# Generated by Django 4.2.4 on 2023-09-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='activo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
