# Generated by Django 4.2.4 on 2023-09-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cod_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=300)),
                ('apellidos', models.CharField(max_length=300)),
                ('direccion', models.CharField(max_length=300)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
    ]
