# Generated by Django 4.2.4 on 2023-09-20 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarioAPP', '0005_remove_documentocompra_activo_inventario_activo'),
        ('clientes', '0001_initial'),
        ('vehiculos', '0002_vehiculos_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=300)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('fecha_entrega', models.DateField(max_length=300)),
                ('estado', models.CharField(blank=True, max_length=30)),
                ('abono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_entregado', models.DateField(null=True)),
                ('fecha_completada', models.DateField(null=True)),
                ('fecha_anulada', models.DateField(null=True)),
                ('cod_cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
                ('id_vehiculo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField()),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.evento')),
                ('nit_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='elemntos_reservados',
            fields=[
                ('id_elemento', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('estado', models.CharField(max_length=30)),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioAPP.inventario')),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.evento')),
            ],
        ),
    ]
